package:
    type:           yii2-extension
    name:           yii2-asset-spicyhost
    title:          'SpicyHost asset files: images, configs and more'
    headline:       SpicyHost assets
    keywords:       spicyhost, asset, extension, yii2
    namespace:      spicyhost\assets\spicyhost
    description:    |
        [SpicyHost](https://spicyhost.com) is a domain registrator.

        This package provides assets shareable between different SpicyHost projects:

        - logos and css bundled with yii2 asset bundle
        - config settings
        - translations

