package:
    type:           yii2-extension
    name:           yii2-asset-spicyhost
    title:          'Spicy Host asset files: images, configs and more'
    headline:       SpicyHost assets
    keywords:       spicyhost, asset, extension, yii2
    namespace:      spicyhost\assets\spicyhost
    description:    |
        [Spicy Host](https://spicyhost.com) provides a superior hosting solution,
        based upon quality hosting and support.

        This package provides assets shareable between different SpicyHost projects:

        - favicon.ico
        - logo and css bundled with yii2 asset bundle
        - config settings
        - translations

